myaac

diff --git a/myaac/Dockerfile b/myaac/Dockerfile
--- a/myaac/Dockerfile
+++ b/myaac/Dockerfile
@@ -1,49 +1,19 @@
-FROM php:8.2-fpm-alpine
+FROM alpine:latest
 
-RUN apk add --no-cache \
-    nginx \
-    supervisor \
-    git \
-    curl \
-    openssl \
-    bash \
-    shadow \
-    npm \
-    libzip-dev \
-    libpng-dev \
-    libxml2-dev \
-    oniguruma-dev \
-    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip opcache \
-    && rm -rf /var/cache/apk/*
-
-COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
-
-RUN adduser -D -h /home/container container
-
-WORKDIR /home/container
-RUN mkdir public && \
-    git config --global --add safe.directory /home/container/public && \
-    git clone https://github.com/slawkens/myaac.git public && \
-    cd public && \
-    composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader && \
-    npm install && \
-    chmod 660 images/guilds && \
-    chmod 660 images/houses && \
-    chmod 660 images/gallery && \
-    chmod -R 760 system/cache
-
-RUN mkdir -p /home/container/tmp/nginx /run/php /var/log/supervisor \
-    && chown -R container:container /home/container /run/php /var/log/supervisor
-
-COPY --chown=container:container nginx.conf /etc/nginx/nginx.conf
-COPY --chown=container:container supervisord.conf /etc/supervisord.conf
-COPY --chown=container:container entrypoint.sh /entrypoint.sh
-RUN chmod +x /entrypoint.sh
+RUN apk --update --no-cache add curl ca-certificates nginx
+RUN apk add php8 php8-xml php8-exif php8-fpm php8-session php8-soap php8-openssl php8-gmp php8-pdo_odbc php8-json php8-dom php8-pdo php8-zip php8-mysqli php8-sqlite3 php8-pdo_pgsql php8-bcmath php8-gd php8-odbc php8-pdo_mysql php8-pdo_sqlite php8-gettext php8-xmlreader php8-bz2 php8-iconv php8-pdo_dblib php8-curl php8-ctype php8-phar php8-fileinfo php8-mbstring php8-tokenizer php8-simplexml
+COPY --from=composer:latest  /usr/bin/composer /usr/bin/composer
 
 USER container
-ENV  USER=container HOME=/home/container
+ENV  USER container
+ENV HOME /home/container
+
 WORKDIR /home/container
+COPY ./entrypoint.sh /entrypoint.sh
 
-EXPOSE 80
+RUN curl -fLo /home/container/nginx.conf https://raw.githubusercontent.com/Limmek/yolks/refs/heads/main/myaac/nginx.conf || { echo "Failed to download nginx config"; exit 1; }
+RUN curl -fLo /home/container/start.sh https://raw.githubusercontent.com/Limmek/yolks/refs/heads/main/myaac/start.sh || { echo "Failed to download start script"; exit 1; } && chmod +x /home/container/start.sh
 
-CMD ["/bin/bash", "/entrypoint.sh"]
+RUN git clone https://github.com/slawkens/myaac.git /home/container/public
+
+CMD ["/bin/ash", "/entrypoint.sh"]
